apiVersion: cr.kanister.io/v1alpha1
kind: Blueprint
metadata: 
  name: cnpg-bp
actions:
  backup:
    outputArtifacts:
      clusterBackup:
        keyValue:
          name: backup-{{ toDate "2006-01-02T15:04:05.999999999Z07:00" .Time | date "2006-01-02T15:04:05Z07:00" | toString | replace ":" "-" | lower }}
    phases:   
      - func: KubeOps
        name: createBackup
        args:
          operation: create
          namespace: "{{ .Object.metadata.namespace }}"
          spec: |-
            apiVersion: postgresql.cnpg.io/v1
            kind: Backup
            metadata:
              name: backup-{{ toDate "2006-01-02T15:04:05.999999999Z07:00" .Time | date "2006-01-02T15:04:05Z07:00" | toString | replace ":" "-" | lower }}
            spec:
              method: barmanObjectStore
              cluster:
                name: {{ .Object.metadata.name }}
  delete:
    inputArtifactNames:
      - cloudObject
    phases:   
      - func: KubeOps
        name: deleteBackup
        args:
          operation: delete
          objectReference:
            group: "postgresql.cnpg.io"
            resource: "backups"
            name: "{{ .ArtifactsIn.cloudObject.KeyValue.name }}"
            namespace: "{{ .Namespace.Name }}"
